openapi: 3.0.1
info:
  title: Todo-Listen-Verwaltung
  description: ""
  contact:
    email: mika.solinsky@t-online.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
servers:
- url: http://127.0.0.1:3000/
tags:
- name: Listenverwaltung
paths:
  /todo-list/{list_id}/entries:
    get:
      tags:
      - Listenverwaltung
      summary: Liefert alle Einträge einer Todo-Liste zurück.
      operationId: getEntries
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: Liste zurükgeliefert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        404:
          description: falsche ID
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
          
  /todo-list/{list_id}:
    delete:
      tags:
      - Listenverwaltung
      summary: Löscht eine komplette Todo-Liste mit allen Einträgen.
      operationId: deleteList
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: Liste wurde gelöscht
          content: 
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Success'
        404:
          description: falsche ID
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
    get:
      tags:
      - Listenverwaltung
      summary: Liefert eine Liste zurück
      operationId: getList
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: Listen zurückgeliefert
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        404: 
          description: falsche ID
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
          
  /todo-list:
    post:
      tags:
      - Listenverwaltung
      summary: Fügt eine neue Todo-Liste hinzu.
      operationId: addList
      requestBody:
        description: list object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
        required: true
      responses:
        200:
          description: Liste hinzugefügt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        400:
          description: Liste konnte nicht hinzugefügt werden
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
          
  /todo-list/{list_id}/entry:
    post:
      tags:
      - Listenverwaltung
      summary: Fügt einen Eintrag zu einer bestehenden Todo-List hinzu.
      operationId: addEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      requestBody:
        description: Entry object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntry'
      responses:
        200:
          description: Eintrag hinzugefügt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
          
  /todo-list/{list_id}/entry/{entry_id}:
    put:
      tags:
      - Listenverwaltung
      summary: Aktualisiert einen bestehenden Eintrag.
      operationId: updateEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      - name: entry_id
        in: path
        description: entry id
        required: true
        schema:
          type: string
      requestBody:
        description: Entry object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntry'
      responses: 
        200:
          description: Eintrag aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        400:
          description: Eintrag konnte nicht aktualisiert werden
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
    delete:
      tags:
      - Listenverwaltung
      summary: Löscht einen einzelnen Eintrag einer Todo-Liste.
      operationId: deleteEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      - name: entry_id
        in: path
        description: entry id
        required: true
        schema:
          type: string
      responses: 
        200:
          description: Eintrag aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        400:
          description: Eintrag konnte nicht aktualisiert werden
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
      x-codegen-request-body-name: body
  /todo-lists:
    get:
      tags:
      - Listenverwaltung
      summary: Liefert alle Todo-Listen zurück
      operationId: getLists
      responses:
        200:
          description: Listen zurückgeliefert
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoList'
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}

components:
  schemas:
    TodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    TodoEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        user_id:
          type: string
          format: uuid
        list_id:
          type: string
          format: uuid
    Success:
      type: object
      properties:
        msg:
          type: string
          